### ISSUE TITLE
I got an error message "Request failed with status code 429"

### ISSUE THREAD

**Issue by jamesxu2018** [SmarterTomato/openai-code-assistant#1]
I got an error message "Request failed with status code 429" when I want it to check a piece of my c snippet.

the steps of what I did
1. select a piece of snippet.
2.  press ctrl+f1
3. type "correct the code" at the diaglog box
4. it returned "Request failed with status code 429"

btw:I've filled up th org-id,and api-key.

**Comment by tommywkzhao** [comment]
State 429 is too many request I believe. Each organisation limited to 20 request per minute. Also I found that sometimes when the server is too busy, that happen to. I will add proper error message next release.
For full list of rate limit, please check here:
https://help.openai.com/en/articles/5955598-is-api-usage-subject-to-any-rate-limits
